### ISSUE TITLE
Style + collapse/expand + remember

### ISSUE THREAD

**Issue by ghost** [frekw/kirby-modules#5]
Did a little make over, and added remember state for collapsed modules, content and settings tab. What you think..? I know you mention that you didn´t like
to incorporate a hidden field in the blueprint, but for me anyway, it definetely beats the
experience over the hidden field... ; ) The field is active..

```
type: image
fields:
    image:
        label: Image
        type: select
        options: images
    active:
        type: hidden
    caption:
        label: Caption
        type: textarea
options:
    size:
        label: Size
        type: text
        width: 4/4
    margin:
        label: Margin
        type: text
        width: 2/4
    padding:
        label: Padding
        type: text
        width: 2/4
```

![accord_style](https://cloud.githubusercontent.com/assets/6350636/14283850/29f01eea-fb45-11e5-967a-96b54ccb2f9c.png)
